### PR TITLE
ignore command name capitalization

### PR DESCRIPTION
**Pull request by BalaM314**
`!Count mega` will now work.

### CODE REVIEW

**Comment by BalaM314** [comment]
This single thing made me build my client with custom arc version.

**Comment by buthed010203** [comment]
I'm just going to assume this works

**Comment by BalaM314** [comment]
Yes, I use it on my custom arc version.
Notes: commandstr is just the command name, so if the command is !builder broken assist self it would be `builder`. This just lowercases the command name before interpreting.

**Comment by buthed010203** [comment]
~~i'm aware, i read the code before merging~~

**Pull request merged**
